server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_test2?createDatabaseIfNotExist=true
    username: root
    password: 16811
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

